In [1]:
import numpy as np

#####  a.	Generate a 2 by 3 matrix containing elements from 1 to 6 and multiply it by a scaler of two

In [16]:
# creating a 2 by 3 matrix
matrix = np.array([[1,2,3,], [4,5,6]])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
scaler = 2 * matrix # multiplied by a scaler of 2
scaler

array([[ 2,  4,  6],
       [ 8, 10, 12]])

#####  b.Create a 3 by 3 identity matrix

In [4]:
# 3 by 3 identity matrix
identity_matrix = np.array([[1,0,0], [0,1,0], [0,0,1]])
print(identity_matrix)

#####  c.	Create a 1-D array call arry1 which contains elements ranging from zero to twenty-seven. Convert arry1 to a                  3-D arry2

In [48]:
arry1 = np.arange(27)

In [49]:
arry2 = arry1.reshape(3,3,3)   # converts the array from 1D to 3D

In [50]:
print(arry2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


#####  d.	Create two 2-D arrays with the first array containing elements from 1 to 6 and the second array containing                        elements from 7 to 12. Horizontally stack the two arrays together.  Using the same set of arrays vertically                     stack the two arrays

In [51]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])

In [54]:
# Horizontal stack
horizontal_stack = np.hstack((arr1,arr2))
horizontal_stack

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [55]:
# vertical stack
vertical_stack = np.vstack((arr1, arr2))
vertical_stack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#####  e.	Create an equally spaced sequence with a gap of 5 ranging from 0 to 100

In [58]:
sequence = np.arange(0,101, 5)
sequence

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

## Pandas

In [17]:
import pandas as pd

## a.

In [38]:
# A dataframe of a list of 5 students
students = pd.DataFrame(['Jude', 'Prince', 'Jane', 'Ruby', 'Jesse'])

In [39]:
students

0
0    Jude
1  Prince
2    Jane
3    Ruby
4   Jesse

## b

In [40]:
# A dictionary of teams and their respective goals in the last five games
team_name = {'Team': ['Dreams', 'RTU', 'King Faisal', 'Samatex', 'Nsoatreman'], 'Goals': [9, 10, 6, 5, 7]}

In [42]:
# creating a dataframe using the dictionary team_name
teams = pd.DataFrame(team_name)
teams

Team  Goals
0       Dreams      9
1          RTU     10
2  King Faisal      6
3      Samatex      5
4   Nsoatreman      7

## c.

In [43]:
# A dictionary of info about some countries in west africa
country_info = {"Country_name": ["Ghana", "Sierra Leone", "Nigeria", "Cote d'ivoire", "Burkina Faso"], 
           "Capitals": ["Accra", "Freetown", "Abuja", "Yamoussoukro", "Ouagadougou"], 
           "Population": [34000000, 23000000, 124000000, 41000000, 46000000]
          }

In [25]:
# creating a dataframe from the dictionary country_info
countries = pd.DataFrame(country_info)
countries

Country_name      Capitals  Population
0          Ghana         Accra    33000000
1           Togo          Lome     2300000
2        Nigeria         Abuja    23400000
3  Cote d'ivoire  Yamoussoukro    45000000
4   Burkina Faso   Ouagadougou    36000000

## d

In [26]:
# a dictionary containing details about Ghana Premier League
league_details = {
    'SNO' : [1, 2, 3, 4, 5, 6, 7],
    'Team' : ['Hearts of Oak', 'Asante Kotoko', 'Ebusau Dwarfs', 'Secondi Hassacas', 'Okwahu United', 'Tano Bofoakwa', 'BA United'],
    'GF' : [120, 90, 90, 80, 78, 70, 71],
    'GA' : [35, 55, 60, 43, 39, 50, 55],
    'PTS' : [80, 60, 60, 55, 53, 49, 44]
}


In [31]:
# creating a dataframe from the dictionary
premier_league = pd.DataFrame(league)

## i

In [33]:
premier_league[['Team', 'GF', 'GA', 'PTS']]

Team   GF  GA  PTS
0     Hearts of Oak  120  35   80
1     Asante Kotoko   90  55   60
2     Ebusau Dwarfs   90  60   60
3  Secondi Hassacas   80  43   55
4     Okwahu United   78  39   53
5     Tano Bofoakwa   70  50   49
6         BA United   71  55   44

## ii

In [45]:
# selecting teams that conceeded more than 30 goals
premier_league[['SNO','Team', 'GF', 'GA', 'PTS']][premier_league['GA' ] > 30]

SNO              Team   GF  GA  PTS
0    1     Hearts of Oak  120  35   80
1    2     Asante Kotoko   90  55   60
2    3     Ebusau Dwarfs   90  60   60
3    4  Secondi Hassacas   80  43   55
4    5     Okwahu United   78  39   53
5    6     Tano Bofoakwa   70  50   49
6    7         BA United   71  55   44

## iii

In [46]:
# selecting teams that scored less than 80 goals
premier_league[['SNO', 'Team', 'GF', 'GA', 'PTS']][premier_league['GF' ] < 80]

SNO           Team  GF  GA  PTS
4    5  Okwahu United  78  39   53
5    6  Tano Bofoakwa  70  50   49
6    7      BA United  71  55   44

## iv

In [47]:
#selecting teams that had less than 60 points
premier_league[['SNO', 'Team', 'GF', 'GA', 'PTS']][premier_league['PTS' ] < 60]

SNO              Team  GF  GA  PTS
3    4  Secondi Hassacas  80  43   55
4    5     Okwahu United  78  39   53
5    6     Tano Bofoakwa  70  50   49
6    7         BA United  71  55   44